### ISSUE TITLE
Ignore format errors if value is empty

### ISSUE THREAD

**Issue by rudasn** [acornejo/jjv#42]
Just a thought if `format` errors should be suppressed if the value is empty.

For example

```js
{
  "type": "string",
  "format": "email"
}
```

should not return an error if the document has an empty string.

**Comment by acornejo** [comment]
I don't think so, since an empty string is NOT a valid email. 

in any case, you should take this question up with the mantainers of the json-schema specification, jjv will comply to whatever the schema dictates (i.e. I do not make up the rules for validation, I only implement them).
