### ISSUE TITLE
Performance Improvement

### ISSUE THREAD

**Issue by ozum** [acornejo/jjv#44]
As I see jjv is great module and has highest number of features among JS based JSON validators. Just a thought. Is it possible to increase performance using a method like "is-my-json-valid" and "json-model" modules use. They generate functions. One of them uses "generate-function", "generate-object-property" modules.

According to [cosmic realms benchmark] (http://cosmicrealms.com/blog/2014/08/29/benchmark-of-node-dot-js-json-validation-modules-part-3/) "is-my-json-valid" is blazing fast.

**Comment by acornejo** [comment]
speed was a concern when designing jjv, but I always prefer simplicity over speed.I'll take a look at is-my-json-valid to see if any of the ideas there can be applied to jjv without complicating the codebase.

**Comment by ozum** [comment]
I totally understand. Just FYI, you can see https://github.com/Muscula/json-schema-benchmark for test results and performance at the same time. jjv has much more feature than is-my-json-valid. Maybe Themis is more comparable to jjv and still uses function generation.

None of them supports draft 5 features like jjv.
