### ISSUE TITLE
"definitions" support

### ISSUE THREAD

**Issue by natlibfi-arlehiko** [acornejo/jjv#55]
It would be great is jjv supported "definitions" (http://json-schema.org/latest/json-schema-validation.html#anchor94).

Definitions allow using a schema defined elsewhere for multiple properties. Referring to a definition is done using a JSON pointer.

**Comment by tvjg** [comment]
`jjv` works correctly with definitions in my personal experience.

```
var subschema = { type: 'string' };
var schema = {
  type: 'object',
  definitions: { subschema: subschema },
  properties: {
    x: { $ref: '#/definitions/subschema' }
  },
  required: ['x']
};
env.validate(schema, { x: 4 });
```
`>> { validation: { x: { type: 'string' } } }`

**Comment by acornejo** [comment]
Correct. It does Support definitions already.

**Comment by natlibfi-arlehiko** [comment]
Sorry, my bad
